### ISSUE TITLE
Password not working

### ISSUE THREAD

**Issue by josephmiller2000** [Yudas1337/NINJA_SHELL#2]
I have tired the default password "IndexAttacker" and hit enter, nothing happens.

**Comment by Yudas1337** [comment]
Sorry, I just realized that the hash in the file was different. you can change the hash password inside $password variable with this value, d9ae02b7c3456bbc23ef73e93bc2c88a. // password is IndexAttacker

so now it should be :
$password = "d9ae02b7c3456bbc23ef73e93bc2c88a"; now . thanks for

**Comment by Yudas1337** [comment]
I have updated the new file , you can re-download it and try again. thanks for the information.
